<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Model;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Orcamento extends \Application\Model\Orcamento implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Application\\Model\\Orcamento' . "\0" . 'id', '' . "\0" . 'Application\\Model\\Orcamento' . "\0" . 'data', '' . "\0" . 'Application\\Model\\Orcamento' . "\0" . 'valor', '' . "\0" . 'Application\\Model\\Orcamento' . "\0" . 'acrescimo', '' . "\0" . 'Application\\Model\\Orcamento' . "\0" . 'desconto', '' . "\0" . 'Application\\Model\\Orcamento' . "\0" . 'status', '' . "\0" . 'Application\\Model\\Orcamento' . "\0" . 'observacao', '' . "\0" . 'Application\\Model\\Orcamento' . "\0" . 'cliente', '' . "\0" . 'Application\\Model\\Orcamento' . "\0" . 'filial', '' . "\0" . 'Application\\Model\\Orcamento' . "\0" . 'usuario'];
        }

        return ['__isInitialized__', '' . "\0" . 'Application\\Model\\Orcamento' . "\0" . 'id', '' . "\0" . 'Application\\Model\\Orcamento' . "\0" . 'data', '' . "\0" . 'Application\\Model\\Orcamento' . "\0" . 'valor', '' . "\0" . 'Application\\Model\\Orcamento' . "\0" . 'acrescimo', '' . "\0" . 'Application\\Model\\Orcamento' . "\0" . 'desconto', '' . "\0" . 'Application\\Model\\Orcamento' . "\0" . 'status', '' . "\0" . 'Application\\Model\\Orcamento' . "\0" . 'observacao', '' . "\0" . 'Application\\Model\\Orcamento' . "\0" . 'cliente', '' . "\0" . 'Application\\Model\\Orcamento' . "\0" . 'filial', '' . "\0" . 'Application\\Model\\Orcamento' . "\0" . 'usuario'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Orcamento $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getData()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData', []);

        return parent::getData();
    }

    /**
     * {@inheritDoc}
     */
    public function setData(\DateTime $data)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setData', [$data]);

        return parent::setData($data);
    }

    /**
     * {@inheritDoc}
     */
    public function getValor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValor', []);

        return parent::getValor();
    }

    /**
     * {@inheritDoc}
     */
    public function setValor(float $valor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValor', [$valor]);

        return parent::setValor($valor);
    }

    /**
     * {@inheritDoc}
     */
    public function getAcrescimo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAcrescimo', []);

        return parent::getAcrescimo();
    }

    /**
     * {@inheritDoc}
     */
    public function setAcrescimo($acrescimo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAcrescimo', [$acrescimo]);

        return parent::setAcrescimo($acrescimo);
    }

    /**
     * {@inheritDoc}
     */
    public function getDesconto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDesconto', []);

        return parent::getDesconto();
    }

    /**
     * {@inheritDoc}
     */
    public function setDesconto($desconto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDesconto', [$desconto]);

        return parent::setDesconto($desconto);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus(string $status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getObservacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservacao', []);

        return parent::getObservacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setObservacao($observacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObservacao', [$observacao]);

        return parent::setObservacao($observacao);
    }

    /**
     * {@inheritDoc}
     */
    public function getCliente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCliente', []);

        return parent::getCliente();
    }

    /**
     * {@inheritDoc}
     */
    public function setCliente(\Application\Model\Cliente $cliente)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCliente', [$cliente]);

        return parent::setCliente($cliente);
    }

    /**
     * {@inheritDoc}
     */
    public function getFilial()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFilial', []);

        return parent::getFilial();
    }

    /**
     * {@inheritDoc}
     */
    public function setFilial(\Application\Model\Filial $filial)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFilial', [$filial]);

        return parent::setFilial($filial);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuario', []);

        return parent::getUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuario(\Application\Model\Usuario $usuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuario', [$usuario]);

        return parent::setUsuario($usuario);
    }

}
