<br>
<h2 class="mt-2"><center>Controle de Lotes</center></h2><hr>
<div class="row justify-content-center align-items-center g-2">
<div class="col d-grid gap-2 ms-5 justify-content-start">
<a class="btn btn-dark align-self-end" href="<?=$this->url('lote', ['action' => 'insert']); ?>" role="button">Nova Entrada</a>
</div>
   <div class="col-2 offset-8 me-4">
   <form action="<?= $this->url('lote', ['action' => 'index']) ?>" method="post">
      <span>Filial: </span>
      <select onchange="this.form.submit();" name="filial" id="filial" class="form-select form-select-md mb-3" aria-label="Selecionar filial">
            <option value="0" <?=$filial == 0 ? 'selected' : '' ?> >Todas </option>
            <?php foreach ($filiais as $item): ?>
               <option value="<?= $item->getId() ?>" <?=$filial == $item->getId() ? 'selected' : '' ?> > <?= $item->getNome() ?> </option>
            <?php endforeach; ?>
      </select>
   </form>
   </div>
</div>

<div class="col-12">
   <hr>
   <table class="table table-hover">
  <thead>
    <tr>
      <th style="width: 20%;" scope="col">Filial</th>
      <th style="width: 20%;" scope="col">Produto</th>
      <th style="width: 10%;" scope="col">Quantidade</th>
      <th style="width: 10%;" scope="col">Lote</th>
      <th style="width: 10%;" scope="col">Validade</th>
      <th style="width: 10%;" scope="col">Entrada</th>
      <th style="width: 10%;" scope="col"></th>
    </tr>
  </thead>
  <tbody>
      <?php foreach ($lotes as $item): ?>
    <tr>
      <td scope="row"><?= $item->getFilial()->getNome() ?></td>
      <td><?= $item->getProduto()->getNome() ?></td>
      <td><?= $item->getQuantidade() ?></td>
      <td><?= $item->getLote() ?></td>
      <td><?= $item->getValidade()->format('d/m/Y') ?></td>
      <td><?= $item->getEntrada()->format('d/m/Y') ?></td>
      <td><a href="<?= $this->url('lote', ['action' => 'edit', 'id' => $item->getId()]) ?>">Alterar</a> </td>
    </tr>    
    <?php endforeach; ?>
  </tbody>
</table>
</div>

