<br>
<h1><center>Entrada de Estoque</center></h1>
<hr>

<div class="pt-5 col-12">
   
<hr>
    <form action="<?=$lote->id ?>" method="post">

            <!-- <input type="hidden" name="ativo" value="1"> -->
                    
            <div class="mb-3">
                <label for="filial" class="form-label">Filial</label>
                <select
                    class="form-select form-select-md"
                    name="filial"
                    id="filial"
                >
                <?php foreach ($filiais as $filial): ?>
                    <option value=<?=$filial->getId()?>><?=$filial->getNome()?></option>
                <?php endforeach; ?>
                </select>
            </div>                     
            <div class="mb-3">
                <label for="produto" class="form-label">Produto</label>
                <select
                    class="form-select form-select-md"
                    name="produto"
                    id="produto"
                >
                <?php foreach ($produtos as $produto): ?>
                    <option value=<?=$produto->getId()?>><?=$produto->getNome()?></option>
                <?php endforeach; ?>
                </select>
            </div>  
            <div class="row">
                <div class="col mb-3">
                    <label for="entrada" class="form-label">Data de Entrada</label>
                    <input
                        type="date"
                        class="form-control"
                        name="entrada"
                        id="entrada"
                        aria-describedby="entrada"
                        value=<?=date('Y-m-d')?>
                    />
                </div>
                <div class="col mb-3">
                    <label for="validade" class="form-label">Validade</label>
                    <input
                        type="date"
                        class="form-control"
                        name="validade"
                        id="validade"
                        aria-describedby="validade"
                    />
                </div>
            </div>
            <div class="row">
                <div class="col mb-3">
                    <label for="quantidade" class="form-label">Quantidade</label>
                    <input
                        type="number"
                        class="form-control"
                        name="quantidade"
                        id="quantidade"
                        aria-describedby="quantidade"
                    />
                </div>
                <div class="col mb-3">
                    <label for="lote" class="form-label">Lote</label>
                    <input
                        type="text"
                        class="form-control"
                        name="lote"
                        id="lote"
                        aria-describedby="lote"
                        placeholder="Lote"
                    />
                </div>
            </div> 
            
            <div class="row">
                <button type="submit" class="col-1 offset-10 btn btn-dark">
                    Adicionar
                </button>
            </div>
            
            
    </form>

</div>


