<div class="pt-5 col-12">
   
<div class="text-center">
    <h3>Editar Categoria: <strong> <?= $categoria->getNome() ?> </strong></h3>
</div><hr>
    <form action="<?=$categoria->getId() ?>" method="post">

            <input type="hidden" name="id" value="<?= $categoria->getId() ?>">
                    
            <div class="mb-3">
                <label for="nome" class="form-label">Nome</label>
                <input
                    type="text"
                    class="form-control"
                    name="nome"
                    id="nome"
                    aria-describedby="Nome"
                    value="<?= $categoria->getNome() ?>"
                />
            </div>
            <div class="row">
                <button type="submit" class="col-1 offset-10 btn btn-dark">
                    Salvar Alterações
                </button>
            </div>
            
            
    </form>

</div>
