<br>
<h1><center>Nova Categoria</center></h1>
<hr>

<div class="pt-5 col-12">
   
<hr>
    <form action="<?=$categoria->id ?>" method="post">
                  
            <div class="mb-3">
                <label for="nome" class="form-label">Nome</label>
                <input
                    type="text"
                    class="form-control"
                    name="nome"
                    id="nome"
                    aria-describedby="Nome"
                    placeholder="Nome"
                />
            </div>       
            <div class="row">
                <button type="submit" class="col-1 offset-10 btn btn-dark">
                    Adicionar Categoria
                </button>
            </div>
            
            
    </form>

</div>
