<br>
<h2 class="mt-2"><center>Controle de Estoque</center></h2><hr>
<div class="row justify-content-center align-items-center g-2">

<div class="col-2 offset-8 me-4">
   <form action="<?= $this->url('estoque', ['action' => 'index']) ?>" method="post">
      <span>Filial: </span>
      <select onchange="this.form.submit();" name="filial" id="filial" class="form-select form-select-md mb-3" aria-label="Selecionar filial">
            <option value="0" <?=$filial == 0 ? 'selected' : '' ?> >Todas </option>
            <?php foreach ($filiais as $item): ?>
               <option value="<?= $item->getId() ?>" <?=$filial == $item->getId() ? 'selected' : '' ?> > <?= $item->getNome() ?> </option>
            <?php endforeach; ?>
      </select>
   </form>
   </div>
</div>

<div class="col-12">
   <hr>
   <table class="table table-hover">
  <thead>
    <tr>
      <th style="width: 20%;" scope="col">Produto</th>
      <th style="width: 10%;" scope="col">Quantidade</th>
      <th style="width: 10%;" scope="col">Menor Validade</th>
    </tr>
  </thead>
  <tbody>
      <?php foreach ($estoque as $item): ?>
      <td><?= $item['produto'] ?></td>
      <td><?= $item['quantidade'] ?></td>
      <td><?= $item['validade']->format('d/m/Y') ?></td>
    </tr>    
    <?php endforeach; ?>
  </tbody>
</table>
</div>

