<br>
<h2 class="mt-2"><center>Orçamentos</center></h2><hr>
<div class="row justify-content-center align-items-center g-2">
<div class="col d-grid gap-2 ms-5 justify-content-start">
<a class="btn btn-dark align-self-end" href="<?=$this->url('orcamento', ['action' => 'insert']); ?>" role="button">Novo Orçamento</a>
</div>
<div class="col-2 offset-8 me-4">
   <form action="<?= $this->url('orcamento', ['action' => 'index']) ?>" method="post">
      <span>Filial: </span>
      <select onchange="this.form.submit();" name="filial" id="filial" class="form-select form-select-md mb-3" aria-label="Selecionar filial">
            <option value="0" <?=$filial == 0 ? 'selected' : '' ?> >Todas </option>
            <?php foreach ($filiais as $item): ?>
               <option value="<?= $item->getId() ?>" <?=$filial == $item->getId() ? 'selected' : '' ?> > <?= $item->getNome() ?> </option>
            <?php endforeach; ?>
      </select>
   </form>
   </div>
</div>

<div class="col-12">
   <hr>
   <table class="table table-hover">
  <thead>
    <tr>
      <th style="width: 10%;" scope="col">Status</th>
      <th style="width: 8%;" scope="col">Orçamento Nº</th>
      <th style="width: 30%;" scope="col">Cliente</th>
      <th style="width: 15%;" scope="col">Data</th>
      <th style="width: 10%;" scope="col">Valor</th>
      <th style="width: 20%;" scope="col">Filial</th>
      <th style="width: 10%;" scope="col"></th>
    </tr>
  </thead>
  <tbody>
      <?php foreach ($orcamentos as $item): ?>
    <tr>
      <td><?= $item->getStatus() ?></td>
      <td><?= $item->getId() ?></td>
      <td><?= $item->getCliente()->getNome() ?></td>
      <td><?= $item->getData()->format('d-m-Y') ?></td>
      <td><?= $item->getValor() ?></td>
      <th scope="row"><?= $item->getFilial()->getNome() ?></th>
      <td><a href="<?= $this->url('orcamento', ['action' => 'edit', 'id' => $item->getId()]) ?>">Alterar</a> </td>
    </tr>    
    <?php endforeach; ?>
  </tbody>
</table>
</div>

