<br>
<h1><center>Novo Usuário</center></h1>
<hr>

<div class="pt-5 col-12">
   
    <form action="<?=$usuario->id ?>" method="post">

            <input type="hidden" name="ativo" value="1">
                    
            <div class="mb-3">
                <label for="nome" class="form-label">Nome</label>
                <input
                    type="text"
                    class="form-control"
                    name="nome"
                    id="nome"
                    aria-describedby="Nome"
                    placeholder="Nome"
                />
            </div>
            <div class="mb-3">
                <label for="email" class="form-label">Email</label>
                <input
                    type="email"
                    class="form-control"
                    name="email"
                    id="email"
                    aria-describedby="emailHelpId"
                    placeholder="E-mail"
                />
            </div>
            <div class="mb-3">
                <label for="senha" class="form-label">Senha</label>
                <input
                    type="password"
                    class="form-control"
                    name="senha"
                    id="senha"
                    placeholder="Senha"
                />
            </div>
            
            <div class="mb-3">
                <label for="tipo" class="form-label">Tipo de Acesso</label>
                <select
                    class="form-select form-select"
                    name="tipo"
                    id="tipo"
                >
                    <option value="comum" selected >Comum</option>
                    <option value="admin">Admin</option>
                </select>
            </div>
            <div class="row">
                <button type="submit" class="col-1 offset-10 btn btn-dark">
                    Adicionar Usuário
                </button>
            </div>
            
            
    </form>

</div>
